spring:
  # H2 Database ??
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #    url: 'jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE'   # H2 DB ?? ?? (In-Memory Mode)
    #    url: 'jdbc:h2:~/expert'    # H2 DB ?? ?? (Embedded Mode)
    username: root        # H2 DB ?? ID (??? ??)
    password: gns09231!!   # H2 DB ?? PW (??? ??)
    url: jdbc:mysql://localhost:3306/expert

  jpa:
    properties:
      hibernate:
        #        dialect: org.hibernate.dialect.H2Dialect
        hbm2ddl:
          auto: update
        show_sql: true             # SQL ?? ?? ???
        format_sql: true           # SQL ?? ??? ???
        use_sql_comments: true     # SQL ??? ?? ?? ???

  # H2 Console ??
  h2:
    console: # H2 DB? ??? ??? ? ?? ??
      enabled: true           # H2 Console ?? ??
      path: /h2       # H2 Console ?? ??

# JWT ??
jwt:
  secret:
    key: 7Iqk7YyM66W07YOA7L2U65Sp7YG065+9U3ByaW5n6rCV7J2Y7Yqc7YSw7LWc7JuQ67mI7J6F64uI64ukLg==